services:
  db:
    image: mysql:8.0
    container_name: mentora-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mentora_db
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: mentora-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - db

volumes:
  db-data:
