import {  StyleSheet, } from "react-native";
import { colors } from "./colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.primary[10],
    paddingTop: 10,
    paddingHorizontal: 20,
  },
  scrollContent: {
    justifyContent: "center",
  },
  title: {
    textAlign: "center",
    fontSize: 24,
    fontWeight: "700",
    color: colors.secondary[60],
    marginBottom: 16,
  },
   subtitle: {
    textAlign: "left",
    fontSize: 16,
    fontWeight: "700",
    color: colors.textNeutral[40],
    marginBottom: 16,
  },
  searchInput: {
    backgroundColor: "#fff",
    width: "90%",
    padding: 10,
    borderRadius: 8,
    borderColor: colors.surfaceDark[30],
    borderWidth: 1,
    marginBottom: 12,
  },
  sortContainer: {
    width: "90%",
    marginBottom: 12,
  },
  sortLabel: {
    fontWeight: "600",
    marginBottom: 6,
    color: colors.textNeutral[40],
  },
  sortButton: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.primary[40],
    marginVertical: 3,
  },
  sortButtonActive: {
    backgroundColor: colors.primary[60],
  },
  msgButton: {
    backgroundColor: colors.secondary[60],
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 6,
  },
  msgButtonText: {
    color: colors.textNeutral[10],
    fontWeight: "600",
  },
  sortButtonText: {
    color: colors.primary[60],
  },
  sortButtonTextActive: {
    color: colors.textNeutral[10],
  },
  headerRow: {
    flexDirection: "row",
    backgroundColor: colors.primary[20],
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 8,
    //width: "90%",
  },
  headerCell: {
    fontWeight: "700",
    color: colors.textNeutral[40],
    textAlign: "center",
  },
  row: {
    //fontWeight: "700",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.textNeutral[10],
    //width: "80%",
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderColor: colors.textNeutral[30],
    //flexWrap: "wrap",
  },
  cell: {
    //flex: 1,
    textAlign: "center",
    color: colors.textNeutral[50],
    paddingHorizontal: 5,
    //flexWrap: "wrap",
  },
  button: {
    //flex: 1,
    backgroundColor: colors.primary[60],
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 6,
    marginHorizontal: 4,
  },
  buttonText: {
    color: colors.textNeutral[10],
    textAlign: "center",
    fontWeight: "600",
  },
  buttonPrimary: {
    backgroundColor: colors.primary[60],
    paddingVertical: 12,
    paddingHorizontal: 40,
    borderRadius: 10,
    marginBottom: 15,
    elevation: 3,
  },
  buttonSecondary: {
    backgroundColor: colors.secondary[60],
    paddingVertical: 12,
    paddingHorizontal: 40,
    borderRadius: 10,
    marginBottom: 15,
    elevation: 3,
  },
  listContainer: {
    width: "100%",
    //alignItems: "center",
    textAlign: "center",
    //paddingBottom: 20,
    //paddingVertical: 5,
    //paddingHorizontal: 10,
  },
  logo: {
    width: 80,
    height: 80,
    alignSelf: "center",
  },
  error: {
    color: colors.accent.danger[40],
    fontSize: 16,
    textAlign: "center",
  },
  cardMain: {
    backgroundColor: colors.surfaceLight[10],
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 20,
    width: "100%",
    maxWidth: 380,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 4,
  },
  cellId: { flex: 2, textAlign: "center" },
  cellName: { flex: 3, textAlign: "left" },
  cellDate: { flex: 2, textAlign: "center" },
  header: { backgroundColor: colors.primary[20], padding: 16, borderRadius: 8, marginBottom: 16 },
  headerTitle: { fontSize: 24, fontWeight: "700", color: colors.secondary[60], marginBottom: 16 },
  contentCard: {
    backgroundColor: "#fff",
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
    shadowColor: colors.surfaceDark[50],
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    elevation: 2,
  },
  loader: { flex: 1, justifyContent: "center", alignItems: "center" },
  contentText: { fontSize: 14, marginBottom: 4 },
  contentFile: { fontStyle: "italic", color: colors.textNeutral[40], marginBottom: 4 },
  contentDate: { fontSize: 12, color: colors.textNeutral[40] },
  chipRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 6,
    flexWrap: "wrap",
  },
  chip: {
    backgroundColor: "#eef2ff",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  chipText: {
    color: "#3730a3",
    fontSize: 12,
    fontWeight: "600",
  },
  chipMuted: {
    backgroundColor: "#f3f4f6",
  },
  chipMutedText: {
    color: "#374151",
  },
  sortContainerBox: {
    width: "90%",
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 8,
  },
  sortLabelBox: {
    marginRight: 8,
    fontWeight: "600",
    marginBottom: 6,
    color: colors.textNeutral[40],
  },
  pickerWrapper: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.textNeutral[10],
    borderRadius: 6,
    overflow: "hidden",
  },
  link: {
    color: "#2563EB",
    textDecorationLine: "underline",
  },
  itemCard: {
    backgroundColor: colors.primary[10],
    padding: 12,
    marginHorizontal: 12,
    marginVertical: 6,
    borderRadius: 8,
    elevation: 1,
  },
    itemRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  name: {
    fontWeight: "700",
  },
  ci: {
    color: colors.textNeutral[40],
  },
  meta: {
    color: colors.textNeutral[40],
    marginTop: 2,
  },
  actionsRow: {
    marginTop: 8,
    flexDirection: "row",
  },
  center: {
    padding: 20,
    alignItems: "center",
  },
  emptyText: {
    color: colors.textNeutral[40],
  },
  errorText: {
    color: "red",
  },
  activityCardItem: {
  backgroundColor: "#fff",
  borderRadius: 12,
  padding: 12,
  marginVertical: 6,
  shadowColor: "#000",
  shadowOpacity: 0.1,
  shadowOffset: { width: 0, height: 2 },
  elevation: 2,
},
activityDescription: {
  fontSize: 15,
  fontWeight: "500",
  color: "#333",
},
activityDate: {
  fontSize: 12,
  color: "#666",
  marginTop: 4,
},
safeArea: {
  flex: 1,
  backgroundColor: colors.surfaceLight[20],
},
});
